name: xUnit.NET Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: password
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 6s
          --health-timeout 6s
          --health-retries 6

    steps:
    - name: Checkout Code
      uses: actions/checkout@v5.1.1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Set Testing Environment
      run: export ASPNETCORE_ENVIRONMENT=Testing
      
    - name: Test
      run: dotnet test
